package com.proofclean.analysis.service;
import com.proofclean.ai.service.AiAnalysisService;import com.proofclean.analysis.dto.*;import com.proofclean.analysis.entity.*;import com.proofclean.analysis.repository.*;import com.proofclean.common.exception.*;import com.proofclean.user.entity.User;import com.proofclean.user.service.UserService;import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.multipart.MultipartFile;import java.util.List;
@Service @RequiredArgsConstructor
public class AnalysisService { private final UserService userService; private final AnalysisProjectRepository projectRepository; private final UploadedFileRepository fileRepository; private final DetectionFindingRepository findingRepository; private final RiskScenarioRepository scenarioRepository; private final RecommendationRepository recommendationRepository; private final AiAnalysisService aiAnalysisService; private final RiskScoringService riskScoringService; private final FileStorageService fileStorageService; private final MaskingService maskingService;
 public User current(String email){ return userService.getByEmail(email); }
 @Transactional public AnalysisResponse create(String email, AnalysisCreateRequest req){ User user=current(email); AnalysisProject p=projectRepository.save(AnalysisProject.builder().user(user).title(req.title()).purpose(req.purpose()).status(AnalysisStatus.CREATED).riskScore(0).build()); return AnalysisResponse.from(p); }
 @Transactional(readOnly=true) public List<AnalysisResponse> list(String email){ return projectRepository.findByUserOrderByCreatedAtDesc(current(email)).stream().map(AnalysisResponse::from).toList(); }
 @Transactional(readOnly=true) public AnalysisDetailResponse detail(String email, Long id){ return AnalysisDetailResponse.from(getOwned(email,id)); }
 public AnalysisProject getOwned(String email, Long id){ AnalysisProject p=projectRepository.findById(id).orElseThrow(()->new NotFoundException("분석 프로젝트를 찾을 수 없습니다.")); if(!p.getUser().getEmail().equals(email)) throw new ForbiddenException("접근 권한이 없습니다."); return p; }
 @Transactional public UploadedFileResponse upload(String email, Long id, MultipartFile file){ AnalysisProject p=getOwned(email,id); UploadedFile saved=fileRepository.save(fileStorageService.store(p,file)); p.setStatus(AnalysisStatus.UPLOADED); projectRepository.save(p); return UploadedFileResponse.from(saved); }
 @Transactional public AnalysisRunResponse run(String email, Long id){ AnalysisProject p=getOwned(email,id); UploadedFile file=p.getFiles().stream().findFirst().orElseThrow(()->new BadRequestException("분석할 파일이 없습니다.")); findingRepository.deleteByAnalysisProject(p); scenarioRepository.deleteByAnalysisProject(p); recommendationRepository.deleteByAnalysisProject(p); p.getFindings().clear(); p.getScenarios().clear(); p.getRecommendations().clear(); var result=aiAnalysisService.analyze(p,file); result.detections().forEach(d->p.getFindings().add(DetectionFinding.builder().analysisProject(p).uploadedFile(file).detectionType(d.detectionType()).label(d.label()).description(d.description()).confidence(d.confidence()).severity(d.severity()).x(d.x()).y(d.y()).width(d.width()).height(d.height()).extractedText(d.extractedText()).build())); result.scenarios().forEach(s->p.getScenarios().add(RiskScenario.builder().analysisProject(p).title(s.title()).scenarioText(s.scenarioText()).riskLevel(s.riskLevel()).build())); result.recommendations().forEach(r->p.getRecommendations().add(Recommendation.builder().analysisProject(p).title(r.title()).description(r.description()).priority(r.priority()).completed(false).build())); p.setRiskScore(riskScoringService.calculate(p.getPurpose(), p.getFindings())); p.setSummary(result.summary()); p.setStatus(AnalysisStatus.ANALYZED); projectRepository.save(p); return new AnalysisRunResponse(p.getId(),p.getRiskScore(),p.getStatus(),p.getFindings().size()); }
 @Transactional(readOnly=true) public List<DetectionDto> findings(String email, Long id){ return getOwned(email,id).getFindings().stream().map(DetectionDto::from).toList(); }
 @Transactional(readOnly=true) public List<RiskScenarioDto> scenarios(String email, Long id){ return getOwned(email,id).getScenarios().stream().map(RiskScenarioDto::from).toList(); }
 @Transactional(readOnly=true) public List<RecommendationDto> recommendations(String email, Long id){ return getOwned(email,id).getRecommendations().stream().map(RecommendationDto::from).toList(); }
 @Transactional public MaskedFileResponse mask(String email, Long id){ AnalysisProject p=getOwned(email,id); UploadedFile source=p.getFiles().stream().findFirst().orElseThrow(()->new BadRequestException("원본 파일이 없습니다.")); MaskedFile masked=maskingService.mask(p,source); p.setStatus(AnalysisStatus.MASKED); p.getMaskedFiles().add(masked); projectRepository.save(p); return MaskedFileResponse.from(masked); }
}
