import { Link, useNavigate } from 'react-router-dom';
import { ArrowRight, CheckCircle2, Eye, FileWarning, LockKeyhole, ScanSearch } from 'lucide-react';
import Header from '../components/layout/Header.jsx';
import Card from '../components/common/Card.jsx';
import useAuth from '../hooks/useAuth.js';

export default function LandingPage() {
  const auth = useAuth();
  const navigate = useNavigate();
  const startDemo = async () => { await auth.demoLogin(); navigate('/dashboard'); };
  return <><Header /><main><section className="hero"><div className="page hero-grid"><div><span className="badge badge-blue">AI 기반 업로드 전 개인정보 노출 가능성 점검</span><h1>올리기 전에,<br />먼저 검사하세요</h1><p className="lead">사진과 문서 속 개인정보 노출 가능성을 확인하고 안전본을 생성합니다. 모든 결과는 탐지 후보이며 최종 확인은 사용자가 직접 진행합니다.</p><div className="row" style={{ marginTop: 28 }}><button className="btn btn-primary" onClick={startDemo}>데모 시작 <ArrowRight size={18} /></button><Link className="btn btn-muted" to="/login">로그인</Link></div></div><div className="hero-preview" id="demo"><div className="preview-glow" /><Card className="mock-window"><div className="between"><div><span className="badge badge-red">위험도 87 · 매우 높음</span><h2>중고거래 게시글 사진 점검</h2></div><span className="badge badge-green">자동 마스킹 완료</span></div><div className="grid grid-2" style={{ marginTop: 18 }}><div className="card card-compact"><b>탐지 후보 4개</b><p className="muted">송장 · 전화번호 · 주소 · 위치 단서</p></div><div className="card card-compact"><b>권장 조치 3개</b><p className="muted">마스킹 후 안전본 확인</p></div></div></Card></div></div></section><section className="section" id="features"><div className="page"><h2 className="section-title">사용자가 놓치기 쉬운 노출 후보</h2><div className="grid grid-4">{[['택배 송장', FileWarning], ['카톡 캡처', ScanSearch], ['모니터 화면', Eye], ['위치 단서', LockKeyhole]].map(([title, Icon]) => <Card key={title}><div className="stat-icon"><Icon size={20} /></div><h3>{title}</h3><p className="muted">업로드 전 확인이 필요한 후보 영역을 시각적으로 표시합니다.</p></Card>)}</div></div></section><section className="section"><div className="page"><h2 className="section-title">분석 흐름</h2><div className="grid grid-4">{['업로드', '탐지 후보 확인', '노출 가능성 분석', '안전본 생성'].map((step, index) => <Card key={step}><span className="badge badge-blue">STEP {index + 1}</span><h3>{step}</h3><p className="muted">복잡한 설정 없이 발표장에서 바로 시연 가능한 흐름입니다.</p></Card>)}</div></div></section><section className="section" id="principles"><div className="page"><Card className="dark-card"><div className="between"><div><h2>보안 원칙</h2><p style={{ color: '#cbd5e1' }}>100% 탐지, 개인정보 확정, 완벽 보호 같은 표현 대신 탐지 후보와 노출 가능성 중심으로 안내합니다.</p></div><CheckCircle2 size={56} color="#14b8a6" /></div></Card></div></section></main><footer className="page" style={{ padding: '30px 0 60px', color: '#64748b' }}>© ProofClean · Human-in-the-loop privacy assistant</footer></>;
}
