package com.proofclean.ai.service;
import com.proofclean.ai.dto.*;import com.proofclean.analysis.entity.*;import org.springframework.stereotype.Service;import java.util.*;
@Service
public class MockAiAnalysisService implements AiAnalysisService {
 public AiAnalysisResult analyze(AnalysisProject project, UploadedFile file){ return switch(project.getPurpose()){ case SECOND_HAND -> secondHand(); case SNS -> sns(); case ASSIGNMENT -> assignment(); case COMMUNITY -> community(); default -> etc(); }; }
 private AiDetectionResult d(DetectionType t,String label,String desc,double c,Severity s,double x,double y,double w,double h,String text){return new AiDetectionResult(t,label,desc,c,s,x,y,w,h,text);} private AiRiskScenarioResult sc(String title,String text,Severity level){return new AiRiskScenarioResult(title,text,level);} private AiRecommendationResult r(String t,String d,int p){return new AiRecommendationResult(t,d,p);} 
 private AiAnalysisResult secondHand(){return new AiAnalysisResult(List.of(d(DetectionType.INVOICE,"송장 정보 후보","택배 송장 영역으로 보이는 후보가 있습니다.",.88,Severity.HIGH,.12,.16,.42,.18,"송장번호 후보"),d(DetectionType.PHONE,"전화번호 후보","연락처 형식의 텍스트 후보가 있습니다.",.84,Severity.HIGH,.56,.22,.28,.08,"010-****-1234"),d(DetectionType.ADDRESS,"주소 후보","주소 또는 상세 위치로 보이는 텍스트 후보가 있습니다.",.81,Severity.CRITICAL,.18,.48,.58,.12,"서울시 **구"),d(DetectionType.LOCATION_HINT,"거래 지역 단서 후보","배경 또는 문구에서 거래 지역 단서가 보일 수 있습니다.",.72,Severity.MEDIUM,.62,.66,.22,.12,"역명 후보")),List.of(sc("생활권 추정 가능성","송장 일부와 거래 지역 정보가 함께 노출될 경우 생활권이 추정될 수 있습니다.",Severity.HIGH)),List.of(r("송장 영역 확인","송장 영역을 블러 처리하세요.",1),r("전화번호 확인","전화번호가 보이는 부분을 가리세요.",2),r("거래 장소 표현 완화","거래 장소가 너무 구체적으로 드러나지 않게 수정하세요.",3)),"송장, 전화번호, 주소로 보이는 탐지 후보가 확인되었습니다. 업로드 전 확인이 필요합니다.");}
 private AiAnalysisResult sns(){return new AiAnalysisResult(List.of(d(DetectionType.FACE,"얼굴 후보","얼굴로 보이는 영역 후보가 있습니다.",.86,Severity.HIGH,.38,.12,.18,.24,""),d(DetectionType.LOCATION_HINT,"위치 단서 후보","간판 또는 배경으로 위치가 추정될 수 있습니다.",.78,Severity.HIGH,.08,.40,.32,.14,"카페명 후보"),d(DetectionType.EXIF,"EXIF 메타데이터 후보","촬영 기기 또는 위치 메타데이터가 포함될 가능성이 있습니다.",.7,Severity.MEDIUM,.70,.08,.20,.10,"GPS 후보"),d(DetectionType.SCREEN_TEXT,"화면 텍스트 후보","캡처 화면의 텍스트 후보가 보입니다.",.74,Severity.MEDIUM,.52,.58,.32,.13,"알림 텍스트 후보")),List.of(sc("방문 장소와 생활 패턴 추정 가능성","사진 속 간판, 촬영 시간, 메타데이터가 함께 노출되면 방문 장소와 생활 패턴이 추정될 수 있습니다.",Severity.HIGH)),List.of(r("배경 단서 확인","위치 단서가 되는 간판이나 창밖 배경을 확인하세요.",1),r("메타데이터 제거","EXIF 메타데이터를 제거하세요.",2)),"위치 단서, 얼굴, 메타데이터 관련 탐지 후보가 확인되었습니다.");}
 private AiAnalysisResult assignment(){return new AiAnalysisResult(List.of(d(DetectionType.STUDENT_ID,"학번 후보","학번 형식으로 보이는 텍스트 후보가 있습니다.",.83,Severity.HIGH,.14,.20,.26,.08,"2024****"),d(DetectionType.EMAIL,"이메일 후보","학교 또는 개인 이메일 후보가 있습니다.",.82,Severity.HIGH,.44,.28,.34,.08,"student@example.edu"),d(DetectionType.SCREEN_TEXT,"화면 텍스트 후보","프로젝트 경로나 저장소명 후보가 보입니다.",.75,Severity.MEDIUM,.16,.52,.48,.12,"github/proofclean"),d(DetectionType.DOCUMENT,"문서 정보 후보","과제명 또는 이름이 함께 보일 수 있습니다.",.69,Severity.MEDIUM,.22,.68,.40,.10,"과제 제출")),List.of(sc("학교 정보 연결 가능성","학번, 이름, 과제명, 저장소명이 함께 노출되면 개인과 학교 정보가 연결될 수 있습니다.",Severity.HIGH)),List.of(r("학번/이름 마스킹","학번과 이름이 들어간 영역을 마스킹하세요.",1),r("저장소명 확인","화면에 보이는 GitHub 저장소명이나 경로를 확인하세요.",2)),"학번, 이메일, 화면 텍스트 후보가 확인되었습니다.");}
 private AiAnalysisResult community(){return new AiAnalysisResult(List.of(d(DetectionType.SCREEN_TEXT,"화면 텍스트 후보","게시글 캡처 내 계정명 후보가 있습니다.",.77,Severity.MEDIUM,.15,.18,.46,.10,"닉네임 후보"),d(DetectionType.EMAIL,"이메일 후보","이메일 형식 후보가 있습니다.",.7,Severity.MEDIUM,.30,.44,.34,.08,"mail@example.com"),d(DetectionType.LOCATION_HINT,"위치 단서 후보","지역명으로 보이는 텍스트 후보가 있습니다.",.65,Severity.MEDIUM,.58,.62,.22,.08,"동네명 후보")),List.of(sc("계정과 지역 연결 가능성","계정 정보와 지역 단서가 함께 노출될 경우 활동 지역이 추정될 수 있습니다.",Severity.MEDIUM)),List.of(r("계정명 확인","닉네임과 이메일 후보를 확인하세요.",1)),"커뮤니티 게시글에 포함된 텍스트 후보를 확인하세요.");}
 private AiAnalysisResult etc(){return new AiAnalysisResult(List.of(d(DetectionType.SCREEN_TEXT,"텍스트 후보","이미지 내 텍스트 후보가 있습니다.",.64,Severity.LOW,.20,.30,.46,.12,"텍스트 후보"),d(DetectionType.EMAIL,"이메일 후보","이메일 형식 후보가 있습니다.",.67,Severity.MEDIUM,.28,.54,.32,.08,"email@example.com")),List.of(sc("식별 정보 조합 가능성","여러 작은 단서가 조합되면 개인 또는 위치 정보로 이어질 수 있습니다.",Severity.MEDIUM)),List.of(r("텍스트 후보 확인","업로드 전 표시된 텍스트 후보를 확인하세요.",1)),"일반 텍스트와 연락처 형식 후보가 확인되었습니다.");}
}
